[package]
name = "aninmals"
version = "0.1.3"
edition = "2018"
description = "Generate aninmals!"
repository = "https://github.com/ninjapiraatti/aninmals"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.0"
